### ISSUE TITLE
deprecated version of minimatc 

### ISSUE THREAD

**Issue by fzahabian** [kesla/node-snappy-stream#4]
I am not able to install snappy-steam due to below error. I believe if we only need to update this package dependencies to use latest snappy version (if that doesn't break the functionality).
`

> sse4_crc32@5.1.1 install /Users/faraz.zahabian/dev/playground/node_modules/snappy-stream/node_modules/fast-crc32c/node_modules/sse4_crc32
> node-gyp rebuild
>   CXX(target) Release/obj.target/crc32c_sse42/src/crc32c_sse42.o
>   LIBTOOL-STATIC Release/crc32c_sse42.a
>   CXX(target) Release/obj.target/sse4_crc32/src/crc32c.o
>   SOLINK_MODULE(target) Release/sse4_crc32.node
> npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
> npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
> npm WARN cannot run in wd snappy@4.1.2 node-gyp rebuild (wd=/Users/faraz.zahabian/dev/playground/node_modules/snappy-stream/node_modules/snappy)``
> `

**Comment by kesla** [comment]
That's just a warning, shouldn't be the reason for you not being able to install this.
