### ISSUE TITLE
Update Snappy Stream to latest version

### ISSUE THREAD

**Issue by mindnuts** [kesla/node-snappy-stream#8]
Hi..can you please update snappystream to latest version? I get the security [warning](https://snyk.io/vuln/npm:minimatch:20160620) in one of our Nodejs App audit process. The snappystream module has already updated dependency for minimatch to latest.

Thanks

**Comment by kesla** [comment]
This is `snappy-stream` not snappystream.

Are you referring to the wrong module? The latest commit of this is a version update.

**Comment by mindnuts** [comment]
@kesla Sorry my bad. I thought this was the right package. For reference, nsqjs package has a dependency on snappystream which has dependency on snappy 4.0.3.
